name = "dockerfiles"
main = "src/index.js"
compatibility_date = "2025-09-06"

[vars]
CUSTOM_DOMAIN = "shijian.qzz.io"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "dev.yourdomain.com"

[env.production]
name = "cloudflare-docker-proxy"
# routes = [
#   { pattern = "docker.libcuda.so", custom_domain = true },
#   { pattern = "quay.libcuda.so", custom_domain = true },
#   { pattern = "gcr.libcuda.so", custom_domain = true },
#   { pattern = "k8s-gcr.libcuda.so", custom_domain = true },
#   { pattern = "k8s.libcuda.so", custom_domain = true },
#   { pattern = "ghcr.libcuda.so", custom_domain = true },
#   { pattern = "cloudsmith.libcuda.so", custom_domain = true },
# ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "docker.libcuda.so"

[env.staging]
name = "cloudflare-docker-proxy-staging"

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "staging.libcuda.so"
